[package]
name = "kube"
version = "0.16.1"
description = "Kubernetes client in the style of client-go"
authors = [
  "clux <sszynrae@gmail.com>",
  "ynqa <un.pensiero.vano@gmail.com>",
]
license-file = "LICENSE"
repository = "https://github.com/clux/kube-rs"
readme = "README.md"
keywords = ["kubernetes", "reflector", "informer", "client-go", "client-rust"]
categories = ["web-programming::http-client"]
edition = "2018"

[dependencies]
base64 = "0.9.3"
chrono = "0.4.6"
dirs = "1.0.4"
failure = "0.1.2"
reqwest = "0.9.17"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
serde_yaml = "0.8.8"
openssl = "0.10.12"
http = "0.1.17"
url = "1.7.2"
log = "0.4.6"
time = "0.1.42"
either = "1.5.2"

[features]
default = []
openapi = ["k8s-openapi"]
rustls-tls = [ "rustls", "reqwest/rustls-tls" ]

[dev-dependencies]
tempfile = "3.0.7"
env_logger = "0.6.1"

[dev-dependencies.k8s-openapi]
version = "0.5.1"
default-features = false
features = ["v1_15"]

[dependencies.rustls]
version = "0.16.0"
optional = true

[dependencies.k8s-openapi]
version = "0.5.1"
default-features = false
features = ["v1_15"]
optional = true
